### PR TITLE
Feb8 logic apps

### PR DESCRIPTION
**Pull request by codemillmatt**
Logic apps article

### CODE REVIEW

**Comment by codemillmatt** [comment]
@Laskewitz - for some reason I can't add you as a reviewer? (I don't know how to github evidently). Anyway, please take a look and rip this to shreds. 😄

**Comment by codemillmatt** [comment]
@nitya - you're probably going to have to fix the metadata ... 🥺

**Comment by codemillmatt** [comment]
Moving this back to draft @nitya & @Laskewitz - I'm not happy with it and I'm going to 🔥 it down and rewrite it.

**Comment by nitya** [comment]
> @nitya - you're probably going to have to fix the metadata ... 🥺

Yep will do - the process we are following is that @SonjaGu  checks the content and merges it with flag still in draft mode. I do metadata fixes and (optional) banner updates and flip flag to publish on the day. Adding @SonjaGu to review.

**Comment by codemillmatt** [comment]
@nitya & @Laskewitz ... I'm back!! 💥 

Daniel - please take a look at the whole article, I left the last part on Power Automate for you 😉 

Nitya - I'm repurposing all the images from the Learn module that I linked to in the resources section. How should we handle credits?

**Comment by Laskewitz** [comment]
@codemillmatt - Added the Power Automate & Logic Apps comparison at the end. 

I added the tracking codes only for the learn site, because I believe they don't track it on the WordPress blogs.

**Comment by codemillmatt** [comment]
@nitya and @SonjaGu - this is good to go!!!!

**Comment by SonjaGu** [comment]
awesome, the blog looks great! merged the pull request

**Pull request merged**
